In [ ]:
from google.colab import drive

# This will prompt for authorization.
drive.mount('/content/drive')
with open('/content/drive/My Drive/majorproject/2ndnew_table_filled.csv', 'r') as file:
    data = file.read()

Mounted at /content/drive

In [ ]:
with open('/content/drive/My Drive/majorproject/GDP_worlddata.csv', 'r') as file:
    data = file.read()

with open('/content/drive/My Drive/majorproject/food_production.csv', 'r') as file:
    data = file.read()

with open('/content/drive/My Drive/majorproject/gdpBook1.csv', 'r') as file:
    data = file.read()

with open('/content/drive/My Drive/majorproject/gdpnewBook1.csv', 'r') as file:
    data = file.read()

with open('/content/drive/My Drive/majorproject/new_gdp.csv', 'r') as file:
    data = file.read()

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

# # Assuming the dataset is stored in a CSV file named 'your_dataset.csv'
# df = pd.read_csv('climate_change.csv')

# Selecting only the 7 specified indicators

In [ ]:

selected_indicators = [
    'AG.LND.ARBL.ZS',
    'AG.LND.IRIG.AG.ZS',
    'AG.LND.PRCP.MM',
    'AG.LND.AGRI.ZS',
    'EN.ATM.CO2E.GF.ZS',
    'EN.CLC.MDAT.ZS',
    'ER.H2O.FWTL.ZS'
]

# Filter the DataFrame to include only the selected indicators and specified countries

In [ ]:

# new_table = df[(df['Indicator Code'].isin(selected_indicators)) &
#                (df['Country Name'].isin(countries_with_non_zero_values))]

# Save the new table to a CSV file

In [ ]:

# new_table.fillna(0, inplace=True)

# new_table.to_csv('2ndnew_table_filled.csv', index=False)

In [ ]:
df = pd.read_csv('2ndnew_table_filled.csv')

unique_country_codes = df['Country Code'].unique()

# Get the number of unique country codes
number_of_country_codes = len(unique_country_codes)

# Print the result
print(f"Number of unique country codes: {number_of_country_codes}")

Number of unique country codes: 101

In [ ]:

# Extract unique country codes and names
unique_country_codes = df['Country Code'].unique()
# unique_country_names = df['Country Name'].unique()

# Print the result
print("List of unique country codes:")
print(unique_country_codes)

# print("\nList of unique country names:")
# print(unique_country_names)

List of unique country codes:
['ABW' 'AFG' 'AGO' 'ALB' 'ARE' 'ARG' 'AUS' 'AUT' 'BEL' 'BGD' 'BGR' 'BHR'
 'BLZ' 'BMU' 'BOL' 'BRA' 'BRB' 'BRN' 'CAN' 'CHE' 'CHL' 'CHN' 'CIV' 'CMR'
 'COD' 'COG' 'COL' 'CUB' 'CYM' 'DNK' 'DOM' 'DZA' 'ECU' 'EGY' 'ESP' 'FIN'
 'FRA' 'FRO' 'GAB' 'GBR' 'GHA' 'GIB' 'GMB' 'GNQ' 'GRC' 'GRL' 'HKG' 'HUN'
 'IDN' 'IND' 'IRL' 'IRN' 'IRQ' 'ISR' 'ITA' 'JOR' 'JPN' 'KOR' 'KWT' 'LBY'
 'LUX' 'MAC' 'MAR' 'MEX' 'MMR' 'MOZ' 'MYS' 'NCL' 'NGA' 'NLD' 'NOR' 'NZL'
 'PAK' 'PER' 'PHL' 'PNG' 'POL' 'PRT' 'PYF' 'QAT' 'ROU' 'RUS' 'RWA' 'SAU'
 'SEN' 'SGP' 'SUR' 'SWE' 'SYR' 'TGO' 'THA' 'TTO' 'TUN' 'TUR' 'TZA' 'URY'
 'USA' 'VEN' 'VNM' 'YEM' 'ZAF']

In [ ]:
df1 = pd.read_csv('food_production.csv')

df1.fillna(0, inplace=True)

df1

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Aruba,ABW,Food production index (2014-2016 = 100),AG.PRD.FOOD.XD,0.0,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
1,Africa Eastern and Southern,AFE,Food production index (2014-2016 = 100),AG.PRD.FOOD.XD,0.0,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
2,Afghanistan,AFG,Food production index (2014-2016 = 100),AG.PRD.FOOD.XD,0.0,41.48,41.81,41.62,45.13,47.25,...,94.29,101.67,95.99,102.34,100.02,96.07,112.55,118.09,113.74,0.0
3,Africa Western and Central,AFW,Food production index (2014-2016 = 100),AG.PRD.FOOD.XD,0.0,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
4,Angola,AGO,Food production index (2014-2016 = 100),AG.PRD.FOOD.XD,0.0,14.65,15.18,15.52,16.24,16.77,...,110.73,97.41,100.32,102.27,103.19,105.59,107.53,112.60,114.59,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,Food production index (2014-2016 = 100),AG.PRD.FOOD.XD,0.0,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
262,"Yemen, Rep.",YEM,Food production index (2014-2016 = 100),AG.PRD.FOOD.XD,0.0,20.94,21.21,21.75,22.18,22.37,...,108.53,108.13,99.62,92.25,91.56,90.93,104.33,108.21,104.92,0.0
263,South Africa,ZAF,Food production index (2014-2016 = 100),AG.PRD.FOOD.XD,0.0,32.21,32.80,34.38,33.21,34.83,...,97.40,102.95,100.99,96.06,105.85,104.32,104.54,111.39,114.31,0.0
264,Zambia,ZMB,Food production index (2014-2016 = 100),AG.PRD.FOOD.XD,0.0,15.68,15.55,15.37,16.16,16.91,...,99.64,105.84,92.53,101.63,124.86,117.76,112.74,122.80,128.88,0.0
265,Zimbabwe,ZWE,Food production index (2014-2016 = 100),AG.PRD.FOOD.XD,0.0,20.82,22.59,21.49,21.39,21.73,...,112.21,96.89,101.19,101.92,106.55,108.86,105.55,109.60,132.04,0.0

In [ ]:
# Filter df1 based on the provided list of country codes
filtered_df1 = df1[df1['Country Code'].isin(unique_country_codes)]

# Print the resulting DataFrame
print(filtered_df1)

             Country Name Country Code  \
0                   Aruba          ABW
2             Afghanistan          AFG
4                  Angola          AGO
5                 Albania          ALB
8    United Arab Emirates          ARE
..                    ...          ...
251         United States          USA
254         Venezuela, RB          VEN
257              Viet Nam          VNM
262           Yemen, Rep.          YEM
263          South Africa          ZAF

                              Indicator Name  Indicator Code  1960   1961  \
0    Food production index (2014-2016 = 100)  AG.PRD.FOOD.XD   0.0   0.00
2    Food production index (2014-2016 = 100)  AG.PRD.FOOD.XD   0.0  41.48
4    Food production index (2014-2016 = 100)  AG.PRD.FOOD.XD   0.0  14.65
5    Food production index (2014-2016 = 100)  AG.PRD.FOOD.XD   0.0  21.34
8    Food production index (2014-2016 = 100)  AG.PRD.FOOD.XD   0.0   4.59
..                                       ...             ...   ...    ...
251  Food production index (2014-2016 = 100)  AG.PRD.FOOD.XD   0.0  41.25
254  Food production index (2014-2016 = 100)  AG.PRD.FOOD.XD   0.0  24.39
257  Food production index (2014-2016 = 100)  AG.PRD.FOOD.XD   0.0  15.77
262  Food production index (2014-2016 = 100)  AG.PRD.FOOD.XD   0.0  20.94
263  Food production index (2014-2016 = 100)  AG.PRD.FOOD.XD   0.0  32.21

      1962   1963   1964   1965  ...    2013    2014    2015    2016    2017  \
0     0.00   0.00   0.00   0.00  ...    0.00    0.00    0.00    0.00    0.00
2    41.81  41.62  45.13  47.25  ...   94.29  101.67   95.99  102.34  100.02
4    15.18  15.52  16.24  16.77  ...  110.73   97.41  100.32  102.27  103.19
5    21.93  20.71  23.37  22.23  ...   95.62   96.82  100.07  103.11  103.90
8     4.66   4.81   5.00   5.11  ...   78.77   94.36   98.36  107.28  107.31
..     ...    ...    ...    ...  ...     ...     ...     ...     ...     ...
251  41.31  42.94  43.49  45.35  ...   95.81   98.13   97.01  104.86  101.96
254  25.01  26.44  28.54  30.42  ...  104.53  105.75  101.45   92.79   88.83
257  16.72  16.73  16.96  16.86  ...   95.90   98.67  100.73  100.60  101.67
262  21.21  21.75  22.18  22.37  ...  108.53  108.13   99.62   92.25   91.56
263  32.80  34.38  33.21  34.83  ...   97.40  102.95  100.99   96.06  105.85

       2018    2019    2020    2021  2022
0      0.00    0.00    0.00    0.00   0.0
2     96.07  112.55  118.09  113.74   0.0
4    105.59  107.53  112.60  114.59   0.0
5    106.08  104.11  105.77  103.44   0.0
8    111.43  114.48  118.28  124.71   0.0
..      ...     ...     ...     ...   ...
251  103.20   99.65  104.05  105.46   0.0
254   82.03   82.12   86.85   85.78   0.0
257  105.31  104.83  106.07  111.65   0.0
262   90.93  104.33  108.21  104.92   0.0
263  104.32  104.54  111.39  114.31   0.0

[101 rows x 67 columns]

In [ ]:
filtered_df1.head(5)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Aruba,ABW,Food production index (2014-2016 = 100),AG.PRD.FOOD.XD,0.0,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
2,Afghanistan,AFG,Food production index (2014-2016 = 100),AG.PRD.FOOD.XD,0.0,41.48,41.81,41.62,45.13,47.25,...,94.29,101.67,95.99,102.34,100.02,96.07,112.55,118.09,113.74,0.0
4,Angola,AGO,Food production index (2014-2016 = 100),AG.PRD.FOOD.XD,0.0,14.65,15.18,15.52,16.24,16.77,...,110.73,97.41,100.32,102.27,103.19,105.59,107.53,112.60,114.59,0.0
5,Albania,ALB,Food production index (2014-2016 = 100),AG.PRD.FOOD.XD,0.0,21.34,21.93,20.71,23.37,22.23,...,95.62,96.82,100.07,103.11,103.90,106.08,104.11,105.77,103.44,0.0
8,United Arab Emirates,ARE,Food production index (2014-2016 = 100),AG.PRD.FOOD.XD,0.0,4.59,4.66,4.81,5.00,5.11,...,78.77,94.36,98.36,107.28,107.31,111.43,114.48,118.28,124.71,0.0

In [ ]:
df3 = pd.read_csv('Book1.csv')

df3.fillna(0, inplace=True)

df3.to_csv('NewBook1.csv', index=False)

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

# Load the dataset
# Replace 'your_dataset.csv' with the actual file path
df = pd.read_csv('your_dataset.csv')

# Select data for the specified indicators
climate_land_data = df[df['Indicator Code'].isin(selected_indicators)]

# Group data by country and indicator for plotting
grouped_data = climate_land_data.groupby(['Country Name', 'Indicator Code']).mean().reset_index()

# Plot time series trends for each indicator across countries
plt.figure(figsize=(15, 8))
for indicator_code, indicator_data in grouped_data.groupby('Indicator Code'):
    for index, row in indicator_data.iterrows():
        values = row.loc['1960':'1967']
        plt.plot(values, label=f"{row['Country Name']} - {indicator_code}")

plt.title('Trends for Selected Climate Change and Land Degradation Indicators')
plt.xlabel('Year')
plt.ylabel('Indicator Value')
plt.legend(loc='center left', bbox_to_anchor=(1, 0.5), title='Country - Indicator Code')
plt.show()

FileNotFoundError: [Errno 2] No such file or directory: 'your_dataset.csv'

In [ ]:
df4 = pd.read_csv('aff_gdp.csv')

df4.fillna(0, inplace=True)

In [ ]:
df4.head(10)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Aruba,ABW,"Agriculture, forestry, and fishing, value adde...",NV.AGR.TOTL.ZS,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.017817,0.014813,0.012520,0.018612,0.023919,0.022253,0.027573,0.000000,0.000000,0.000000
1,Africa Eastern and Southern,AFE,"Agriculture, forestry, and fishing, value adde...",NV.AGR.TOTL.ZS,0.0,0.0,0.0,0.0,0.0,0.000000,...,11.603396,12.526531,13.528791,13.686914,13.400668,11.916415,12.637198,14.647070,13.404936,13.858659
2,Afghanistan,AFG,"Agriculture, forestry, and fishing, value adde...",NV.AGR.TOTL.ZS,0.0,0.0,0.0,0.0,0.0,0.000000,...,22.810663,22.137041,20.634323,25.740314,26.420199,22.042897,25.773971,29.975583,33.597619,0.000000
3,Africa Western and Central,AFW,"Agriculture, forestry, and fishing, value adde...",NV.AGR.TOTL.ZS,0.0,0.0,0.0,0.0,0.0,0.000000,...,19.608271,19.229726,20.255694,20.572590,20.434883,20.488261,20.767276,22.511019,21.673421,21.959686
4,Angola,AGO,"Agriculture, forestry, and fishing, value adde...",NV.AGR.TOTL.ZS,0.0,0.0,0.0,0.0,0.0,0.000000,...,6.507492,7.547057,9.122534,9.831169,10.016996,8.607742,7.882625,9.946544,11.486345,13.649109
5,Albania,ALB,"Agriculture, forestry, and fishing, value adde...",NV.AGR.TOTL.ZS,0.0,0.0,0.0,0.0,0.0,0.000000,...,19.565158,19.990181,19.780214,19.849994,19.022127,18.429495,18.389332,19.225223,18.358125,18.622821
6,Andorra,AND,"Agriculture, forestry, and fishing, value adde...",NV.AGR.TOTL.ZS,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.585559,0.537623,0.513420,0.522000,0.559539,0.546368,0.522633,0.559443,0.533618,0.495686
7,Arab World,ARB,"Agriculture, forestry, and fishing, value adde...",NV.AGR.TOTL.ZS,0.0,0.0,0.0,0.0,0.0,0.000000,...,5.023373,5.306089,6.039971,5.926960,5.579353,4.688765,4.947446,5.639859,4.937267,4.352709
8,United Arab Emirates,ARE,"Agriculture, forestry, and fishing, value adde...",NV.AGR.TOTL.ZS,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.633172,0.628716,0.723672,0.750863,0.761758,0.711464,0.746712,0.963891,0.943418,0.823740
9,Argentina,ARG,"Agriculture, forestry, and fishing, value adde...",NV.AGR.TOTL.ZS,0.0,0.0,0.0,0.0,0.0,12.904163,...,6.052918,6.712704,5.156686,6.264566,5.231622,4.537879,5.318556,6.357034,7.306309,6.639898

In [ ]:
filtered_df4 = df4[df1['Country Code'].isin(unique_country_codes)]

# Print the resulting DataFrame
print(filtered_df4)

             Country Name Country Code  \
0                   Aruba          ABW
2             Afghanistan          AFG
4                  Angola          AGO
5                 Albania          ALB
8    United Arab Emirates          ARE
..                    ...          ...
251         United States          USA
254         Venezuela, RB          VEN
257              Viet Nam          VNM
262           Yemen, Rep.          YEM
263          South Africa          ZAF

                                        Indicator Name  Indicator Code  \
0    Agriculture, forestry, and fishing, value adde...  NV.AGR.TOTL.ZS
2    Agriculture, forestry, and fishing, value adde...  NV.AGR.TOTL.ZS
4    Agriculture, forestry, and fishing, value adde...  NV.AGR.TOTL.ZS
5    Agriculture, forestry, and fishing, value adde...  NV.AGR.TOTL.ZS
8    Agriculture, forestry, and fishing, value adde...  NV.AGR.TOTL.ZS
..                                                 ...             ...
251  Agriculture, forestry, and fishing, value adde...  NV.AGR.TOTL.ZS
254  Agriculture, forestry, and fishing, value adde...  NV.AGR.TOTL.ZS
257  Agriculture, forestry, and fishing, value adde...  NV.AGR.TOTL.ZS
262  Agriculture, forestry, and fishing, value adde...  NV.AGR.TOTL.ZS
263  Agriculture, forestry, and fishing, value adde...  NV.AGR.TOTL.ZS

         1960      1961      1962     1963     1964      1965  ...       2013  \
0    0.000000  0.000000  0.000000  0.00000  0.00000  0.000000  ...   0.017817
2    0.000000  0.000000  0.000000  0.00000  0.00000  0.000000  ...  22.810663
4    0.000000  0.000000  0.000000  0.00000  0.00000  0.000000  ...   6.507492
5    0.000000  0.000000  0.000000  0.00000  0.00000  0.000000  ...  19.565158
8    0.000000  0.000000  0.000000  0.00000  0.00000  0.000000  ...   0.633172
..        ...       ...       ...      ...      ...       ...  ...        ...
251  0.000000  0.000000  0.000000  0.00000  0.00000  0.000000  ...   1.321084
254  0.000000  0.000000  0.000000  0.00000  0.00000  0.000000  ...   4.902550
257  0.000000  0.000000  0.000000  0.00000  0.00000  0.000000  ...  15.215612
262  0.000000  0.000000  0.000000  0.00000  0.00000  0.000000  ...  17.684985
263  9.041447  9.317147  8.958631  8.83529  7.64637  7.434387  ...   1.926849

          2014       2015       2016       2017       2018       2019  \
0     0.014813   0.012520   0.018612   0.023919   0.022253   0.027573
2    22.137041  20.634323  25.740314  26.420199  22.042897  25.773971
4     7.547057   9.122534   9.831169  10.016996   8.607742   7.882625
5    19.990181  19.780214  19.849994  19.022127  18.429495  18.389332
8     0.628716   0.723672   0.750863   0.761758   0.711464   0.746712
..         ...        ...        ...        ...        ...        ...
251   1.172065   1.033934   0.942645   0.946869   0.903901   0.838813
254   5.026754   0.000000   0.000000   0.000000   0.000000   0.000000
257  14.880349  14.474726  13.818255  12.929879  12.306668  11.784529
262  17.676574  20.205937  25.090913  26.961066  28.745140   0.000000
263   2.125749   2.233978   2.414186   2.493799   2.260704   1.950321

          2020       2021       2022
0     0.000000   0.000000   0.000000
2    29.975583  33.597619   0.000000
4     9.946544  11.486345  13.649109
5    19.225223  18.358125  18.622821
8     0.963891   0.943418   0.823740
..         ...        ...        ...
251   0.948847   0.959567   0.000000
254   0.000000   0.000000   0.000000
257  12.655404  12.560370  11.877108
262   0.000000   0.000000   0.000000
263   2.582420   2.557299   2.830275

[101 rows x 67 columns]

In [ ]:
filtered_df4.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Aruba,ABW,"Agriculture, forestry, and fishing, value adde...",NV.AGR.TOTL.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,0.017817,0.014813,0.012520,0.018612,0.023919,0.022253,0.027573,0.000000,0.000000,0.000000
2,Afghanistan,AFG,"Agriculture, forestry, and fishing, value adde...",NV.AGR.TOTL.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,22.810663,22.137041,20.634323,25.740314,26.420199,22.042897,25.773971,29.975583,33.597619,0.000000
4,Angola,AGO,"Agriculture, forestry, and fishing, value adde...",NV.AGR.TOTL.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,6.507492,7.547057,9.122534,9.831169,10.016996,8.607742,7.882625,9.946544,11.486345,13.649109
5,Albania,ALB,"Agriculture, forestry, and fishing, value adde...",NV.AGR.TOTL.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,19.565158,19.990181,19.780214,19.849994,19.022127,18.429495,18.389332,19.225223,18.358125,18.622821
8,United Arab Emirates,ARE,"Agriculture, forestry, and fishing, value adde...",NV.AGR.TOTL.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,0.633172,0.628716,0.723672,0.750863,0.761758,0.711464,0.746712,0.963891,0.943418,0.823740

In [ ]:
filtered_df4.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Aruba,ABW,"Agriculture, forestry, and fishing, value adde...",NV.AGR.TOTL.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,0.017817,0.014813,0.012520,0.018612,0.023919,0.022253,0.027573,0.000000,0.000000,0.000000
2,Afghanistan,AFG,"Agriculture, forestry, and fishing, value adde...",NV.AGR.TOTL.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,22.810663,22.137041,20.634323,25.740314,26.420199,22.042897,25.773971,29.975583,33.597619,0.000000
4,Angola,AGO,"Agriculture, forestry, and fishing, value adde...",NV.AGR.TOTL.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,6.507492,7.547057,9.122534,9.831169,10.016996,8.607742,7.882625,9.946544,11.486345,13.649109
5,Albania,ALB,"Agriculture, forestry, and fishing, value adde...",NV.AGR.TOTL.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,19.565158,19.990181,19.780214,19.849994,19.022127,18.429495,18.389332,19.225223,18.358125,18.622821
8,United Arab Emirates,ARE,"Agriculture, forestry, and fishing, value adde...",NV.AGR.TOTL.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,0.633172,0.628716,0.723672,0.750863,0.761758,0.711464,0.746712,0.963891,0.943418,0.823740

In [ ]:
columns_to_drop = ['Country Name', 'Indicator Name', 'Indicator Code']
filtered_df4.drop(columns=columns_to_drop, inplace=True)

# Display the modified DataFrame
print(filtered_df4)

    Country Code      1960      1961      1962     1963     1964      1965  \
0            ABW  0.000000  0.000000  0.000000  0.00000  0.00000  0.000000
2            AFG  0.000000  0.000000  0.000000  0.00000  0.00000  0.000000
4            AGO  0.000000  0.000000  0.000000  0.00000  0.00000  0.000000
5            ALB  0.000000  0.000000  0.000000  0.00000  0.00000  0.000000
8            ARE  0.000000  0.000000  0.000000  0.00000  0.00000  0.000000
..           ...       ...       ...       ...      ...      ...       ...
251          USA  0.000000  0.000000  0.000000  0.00000  0.00000  0.000000
254          VEN  0.000000  0.000000  0.000000  0.00000  0.00000  0.000000
257          VNM  0.000000  0.000000  0.000000  0.00000  0.00000  0.000000
262          YEM  0.000000  0.000000  0.000000  0.00000  0.00000  0.000000
263          ZAF  9.041447  9.317147  8.958631  8.83529  7.64637  7.434387

         1966      1967      1968  ...       2013       2014       2015  \
0    0.000000  0.000000  0.000000  ...   0.017817   0.014813   0.012520
2    0.000000  0.000000  0.000000  ...  22.810663  22.137041  20.634323
4    0.000000  0.000000  0.000000  ...   6.507492   7.547057   9.122534
5    0.000000  0.000000  0.000000  ...  19.565158  19.990181  19.780214
8    0.000000  0.000000  0.000000  ...   0.633172   0.628716   0.723672
..        ...       ...       ...  ...        ...        ...        ...
251  0.000000  0.000000  0.000000  ...   1.321084   1.172065   1.033934
254  0.000000  0.000000  6.449784  ...   4.902550   5.026754   0.000000
257  0.000000  0.000000  0.000000  ...  15.215612  14.880349  14.474726
262  0.000000  0.000000  0.000000  ...  17.684985  17.676574  20.205937
263  7.703675  8.494823  7.137018  ...   1.926849   2.125749   2.233978

          2016       2017       2018       2019       2020       2021  \
0     0.018612   0.023919   0.022253   0.027573   0.000000   0.000000
2    25.740314  26.420199  22.042897  25.773971  29.975583  33.597619
4     9.831169  10.016996   8.607742   7.882625   9.946544  11.486345
5    19.849994  19.022127  18.429495  18.389332  19.225223  18.358125
8     0.750863   0.761758   0.711464   0.746712   0.963891   0.943418
..         ...        ...        ...        ...        ...        ...
251   0.942645   0.946869   0.903901   0.838813   0.948847   0.959567
254   0.000000   0.000000   0.000000   0.000000   0.000000   0.000000
257  13.818255  12.929879  12.306668  11.784529  12.655404  12.560370
262  25.090913  26.961066  28.745140   0.000000   0.000000   0.000000
263   2.414186   2.493799   2.260704   1.950321   2.582420   2.557299

          2022
0     0.000000
2     0.000000
4    13.649109
5    18.622821
8     0.823740
..         ...
251   0.000000
254   0.000000
257  11.877108
262   0.000000
263   2.830275

[101 rows x 64 columns]

<ipython-input-38-10e06b052481>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df4.drop(columns=columns_to_drop, inplace=True)

In [ ]:
# Convert numeric columns to numeric type, replacing non-numeric values with NaN
filtered_df4.iloc[:, 1:-1] = filtered_df4.iloc[:, 1:-1].apply(pd.to_numeric, errors='coerce')

# Create a new column 'Combined' with the median of values from '1960' to '1965'
filtered_df4['median_aff'] = filtered_df4.iloc[:, 1:-1].median(axis=1)


# Display the resulting DataFrame with the new 'Combined' column
print(filtered_df4[['Country Code', 'median_aff']])

    Country Code  median_aff
0            ABW    0.000000
2            AFG    0.000000
4            AGO    0.000000
5            ALB    0.000000
8            ARE    0.740869
..           ...         ...
251          USA    0.000000
254          VEN    4.951839
257          VNM   13.374067
262          YEM    0.000000
263          ZAF    3.749476

[101 rows x 2 columns]

<ipython-input-39-0028ef8e7898>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df4.iloc[:, 1:-1] = filtered_df4.iloc[:, 1:-1].apply(pd.to_numeric, errors='coerce')
<ipython-input-39-0028ef8e7898>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df4['median_aff'] = filtered_df4.iloc[:, 1:-1].median(axis=1)

In [ ]:
low_threshold = filtered_df4['median_aff'].quantile(0.33)
high_threshold = filtered_df4['median_aff'].quantile(0.66)

# Categorize based on thresholds
filtered_df4['Category_median_aff'] = pd.cut(filtered_df4['median_aff'], bins=[-float('inf'), low_threshold, high_threshold, float('inf')],
                               labels=['Low', 'Moderate', 'High'])

# Display the result
print(filtered_df4[['Country Code', 'median_aff', 'Category_median_aff']])

    Country Code  median_aff Category_median_aff
0            ABW    0.000000                 Low
2            AFG    0.000000                 Low
4            AGO    0.000000                 Low
5            ALB    0.000000                 Low
8            ARE    0.740869            Moderate
..           ...         ...                 ...
251          USA    0.000000                 Low
254          VEN    4.951839            Moderate
257          VNM   13.374067                High
262          YEM    0.000000                 Low
263          ZAF    3.749476            Moderate

[101 rows x 3 columns]

<ipython-input-40-db5d3470a145>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df4['Category_median_aff'] = pd.cut(filtered_df4['median_aff'], bins=[-float('inf'), low_threshold, high_threshold, float('inf')],

In [ ]:
df5 = pd.read_csv('fertilizer.csv')

df5.fillna(0, inplace=True)

In [ ]:
filtered_df5 = df5[df1['Country Code'].isin(unique_country_codes)]

# Print the resulting DataFrame
print(filtered_df5)

             Country Name Country Code  \
0                   Aruba          ABW
2             Afghanistan          AFG
4                  Angola          AGO
5                 Albania          ALB
8    United Arab Emirates          ARE
..                    ...          ...
251         United States          USA
254         Venezuela, RB          VEN
257              Viet Nam          VNM
262           Yemen, Rep.          YEM
263          South Africa          ZAF

                                        Indicator Name     Indicator Code  \
0    Fertilizer consumption (% of fertilizer produc...  AG.CON.FERT.PT.ZS
2    Fertilizer consumption (% of fertilizer produc...  AG.CON.FERT.PT.ZS
4    Fertilizer consumption (% of fertilizer produc...  AG.CON.FERT.PT.ZS
5    Fertilizer consumption (% of fertilizer produc...  AG.CON.FERT.PT.ZS
8    Fertilizer consumption (% of fertilizer produc...  AG.CON.FERT.PT.ZS
..                                                 ...                ...
251  Fertilizer consumption (% of fertilizer produc...  AG.CON.FERT.PT.ZS
254  Fertilizer consumption (% of fertilizer produc...  AG.CON.FERT.PT.ZS
257  Fertilizer consumption (% of fertilizer produc...  AG.CON.FERT.PT.ZS
262  Fertilizer consumption (% of fertilizer produc...  AG.CON.FERT.PT.ZS
263  Fertilizer consumption (% of fertilizer produc...  AG.CON.FERT.PT.ZS

     1960        1961        1962        1963         1964        1965  ...  \
0     0.0    0.000000    0.000000    0.000000     0.000000    0.000000  ...
2     0.0    0.000000    0.000000    0.000000     0.000000    0.000000  ...
4     0.0    0.000000    0.000000    0.000000     0.000000    0.000000  ...
5     0.0    0.000000    0.000000    0.000000  1280.000000  400.000000  ...
8     0.0    0.000000    0.000000    0.000000     0.000000    0.000000  ...
..    ...         ...         ...         ...          ...         ...  ...
251   0.0   92.016399   93.628184   92.345584    92.103607   90.536841  ...
254   0.0  950.000000  800.000000  152.941177   173.684211  140.000000  ...
257   0.0  118.666667  118.750000  109.375000   113.580247  120.000000  ...
262   0.0    0.000000    0.000000    0.000000     0.000000    0.000000  ...
263   0.0  137.098441  129.266704  128.260870   145.105485  143.629191  ...

           2013        2014        2015        2016        2017        2018  \
0      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
2    220.576394  495.085918  648.396816  662.617347  986.802156  847.548223
4      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
5      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
8      5.887981    2.966575    3.378659    3.378659    3.378659    3.378659
..          ...         ...         ...         ...         ...         ...
251  127.151943  121.210472  123.115599  117.267980  110.404233  109.304071
254  104.733406   83.502604   96.170740   67.923145   62.889746  102.624091
257  216.890357  183.604927  218.846285  208.620989  208.001286  193.904358
262    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
263  235.739232  184.784623  238.459100  203.555556  237.990196  281.166765

           2019        2020        2021  2022
0      0.000000    0.000000    0.000000   0.0
2    535.525663  427.560193  255.254371   0.0
4      0.000000    0.000000    0.000000   0.0
5      0.000000    0.000000    0.000000   0.0
8      3.378659    3.378659    3.378659   0.0
..          ...         ...         ...   ...
251  105.437340  106.467421  112.265836   0.0
254   38.749017   67.275781   67.918342   0.0
257  180.213515  180.213515  180.213515   0.0
262    0.000000    0.000000    0.000000   0.0
263  332.274271  338.433151  375.722885   0.0

[101 rows x 67 columns]

In [ ]:

import pandas as pd


columns_to_drop = ['Country Name', 'Indicator Name', 'Indicator Code']
filtered_df5.drop(columns=columns_to_drop, inplace=True)

# Display the modified DataFrame
print(filtered_df5)

    Country Code  1960        1961        1962        1963         1964  \
0            ABW   0.0    0.000000    0.000000    0.000000     0.000000
2            AFG   0.0    0.000000    0.000000    0.000000     0.000000
4            AGO   0.0    0.000000    0.000000    0.000000     0.000000
5            ALB   0.0    0.000000    0.000000    0.000000  1280.000000
8            ARE   0.0    0.000000    0.000000    0.000000     0.000000
..           ...   ...         ...         ...         ...          ...
251          USA   0.0   92.016399   93.628184   92.345584    92.103607
254          VEN   0.0  950.000000  800.000000  152.941177   173.684211
257          VNM   0.0  118.666667  118.750000  109.375000   113.580247
262          YEM   0.0    0.000000    0.000000    0.000000     0.000000
263          ZAF   0.0  137.098441  129.266704  128.260870   145.105485

           1965        1966        1967         1968  ...        2013  \
0      0.000000    0.000000    0.000000     0.000000  ...    0.000000
2      0.000000    0.000000    0.000000     0.000000  ...  220.576394
4      0.000000    0.000000    0.000000     0.000000  ...    0.000000
5    400.000000  316.666667  155.000000   119.354839  ...    0.000000
8      0.000000    0.000000    0.000000     0.000000  ...    5.887981
..          ...         ...         ...          ...  ...         ...
251   90.536841   93.200783   94.642349    97.614742  ...  127.151943
254  140.000000  147.313043  160.011111   181.369221  ...  104.733406
257  120.000000  139.393939  646.922222  1621.342857  ...  216.890357
262    0.000000    0.000000    0.000000     0.000000  ...    0.000000
263  143.629191  134.984227  101.548054   119.612934  ...  235.739232

           2014        2015        2016        2017        2018        2019  \
0      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
2    495.085918  648.396816  662.617347  986.802156  847.548223  535.525663
4      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
5      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
8      2.966575    3.378659    3.378659    3.378659    3.378659    3.378659
..          ...         ...         ...         ...         ...         ...
251  121.210472  123.115599  117.267980  110.404233  109.304071  105.437340
254   83.502604   96.170740   67.923145   62.889746  102.624091   38.749017
257  183.604927  218.846285  208.620989  208.001286  193.904358  180.213515
262    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
263  184.784623  238.459100  203.555556  237.990196  281.166765  332.274271

           2020        2021  2022
0      0.000000    0.000000   0.0
2    427.560193  255.254371   0.0
4      0.000000    0.000000   0.0
5      0.000000    0.000000   0.0
8      3.378659    3.378659   0.0
..          ...         ...   ...
251  106.467421  112.265836   0.0
254   67.275781   67.918342   0.0
257  180.213515  180.213515   0.0
262    0.000000    0.000000   0.0
263  338.433151  375.722885   0.0

[101 rows x 64 columns]

<ipython-input-43-ebbf324b4f5e>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df5.drop(columns=columns_to_drop, inplace=True)

In [ ]:
# Convert numeric columns to numeric type, replacing non-numeric values with NaN
filtered_df5.iloc[:, 1:-1] = filtered_df5.iloc[:, 1:-1].apply(pd.to_numeric, errors='coerce')

# Create a new column 'Combined' with the median of values from '1960' to '1965'
filtered_df5['median_fertilizer'] = filtered_df5.iloc[:, 1:-1].median(axis=1)


# Display the resulting DataFrame with the new 'Combined' column
print(filtered_df5[['Country Code', 'median_fertilizer']])

    Country Code  median_fertilizer
0            ABW           0.000000
2            AFG         104.651853
4            AGO           0.000000
5            ALB         101.111029
8            ARE           3.378659
..           ...                ...
251          USA          96.995417
254          VEN          87.754044
257          VNM         363.201620
262          YEM           0.000000
263          ZAF         117.706018

[101 rows x 2 columns]

<ipython-input-44-57853d141306>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df5.iloc[:, 1:-1] = filtered_df5.iloc[:, 1:-1].apply(pd.to_numeric, errors='coerce')
<ipython-input-44-57853d141306>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df5['median_fertilizer'] = filtered_df5.iloc[:, 1:-1].median(axis=1)

In [ ]:
low_threshold = filtered_df5['median_fertilizer'].quantile(0.33)
high_threshold = filtered_df5['median_fertilizer'].quantile(0.66)

# Categorize based on thresholds
filtered_df5['Category_median_fertilizer'] = pd.cut(filtered_df5['median_fertilizer'], bins=[-float('inf'), low_threshold, high_threshold, float('inf')],
                               labels=['Low', 'Moderate', 'High'])

# Display the result
print(filtered_df5[['Country Code', 'median_fertilizer', 'Category_median_fertilizer']])

    Country Code  median_fertilizer Category_median_fertilizer
0            ABW           0.000000                        Low
2            AFG         104.651853                   Moderate
4            AGO           0.000000                        Low
5            ALB         101.111029                   Moderate
8            ARE           3.378659                   Moderate
..           ...                ...                        ...
251          USA          96.995417                   Moderate
254          VEN          87.754044                   Moderate
257          VNM         363.201620                       High
262          YEM           0.000000                        Low
263          ZAF         117.706018                       High

[101 rows x 3 columns]

<ipython-input-45-88318157f69e>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df5['Category_median_fertilizer'] = pd.cut(filtered_df5['median_fertilizer'], bins=[-float('inf'), low_threshold, high_threshold, float('inf')],

In [ ]:
df7 = pd.read_csv('GDP_worlddata.csv')

df7.fillna(0, inplace=True)

In [ ]:
filtered_df7 = df7[df1['Country Code'].isin(unique_country_codes)]

# Print the resulting DataFrame
print(filtered_df7)

             Country Name Country Code     Indicator Name  Indicator Code  \
0                   Aruba          ABW  GDP (current US$)  NY.GDP.MKTP.CD
2             Afghanistan          AFG  GDP (current US$)  NY.GDP.MKTP.CD
4                  Angola          AGO  GDP (current US$)  NY.GDP.MKTP.CD
5                 Albania          ALB  GDP (current US$)  NY.GDP.MKTP.CD
8    United Arab Emirates          ARE  GDP (current US$)  NY.GDP.MKTP.CD
..                    ...          ...                ...             ...
251         United States          USA  GDP (current US$)  NY.GDP.MKTP.CD
254         Venezuela, RB          VEN  GDP (current US$)  NY.GDP.MKTP.CD
257              Viet Nam          VNM  GDP (current US$)  NY.GDP.MKTP.CD
262           Yemen, Rep.          YEM  GDP (current US$)  NY.GDP.MKTP.CD
263          South Africa          ZAF  GDP (current US$)  NY.GDP.MKTP.CD

             1960          1961          1962          1963          1964  \
0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
2    5.377778e+08  5.488889e+08  5.466667e+08  7.511112e+08  8.000000e+08
4    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
5    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
8    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
..            ...           ...           ...           ...           ...
251  5.433000e+11  5.633000e+11  6.051000e+11  6.386000e+11  6.858000e+11
254  7.663938e+09  8.067267e+09  8.814310e+09  9.608717e+09  8.192414e+09
257  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
262  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
263  8.748597e+09  9.225996e+09  9.813996e+09  1.085420e+10  1.195600e+10

             1965  ...          2013          2014          2015  \
0    0.000000e+00  ...  2.727850e+09  2.790850e+09  2.962907e+09
2    1.006667e+09  ...  2.014642e+10  2.049713e+10  1.913422e+10
4    0.000000e+00  ...  1.323390e+11  1.359670e+11  9.049642e+10
5    0.000000e+00  ...  1.277622e+10  1.322815e+10  1.138685e+10
8    0.000000e+00  ...  4.002190e+11  4.141050e+11  3.702750e+11
..            ...  ...           ...           ...           ...
251  7.437000e+11  ...  1.684320e+13  1.755070e+13  1.820600e+13
254  8.427778e+09  ...  3.710050e+11  4.823590e+11  0.000000e+00
257  0.000000e+00  ...  2.137090e+11  2.334510e+11  2.392580e+11
262  0.000000e+00  ...  4.041523e+10  4.322859e+10  4.244449e+10
263  1.306899e+10  ...  4.008860e+11  3.811990e+11  3.467100e+11

             2016          2017          2018          2019          2020  \
0    2.983635e+09  3.092429e+09  3.276184e+09  3.395799e+09  2.558906e+09
2    1.811657e+10  1.875346e+10  1.805322e+10  1.879944e+10  1.995593e+10
4    5.276162e+10  7.369016e+10  7.945069e+10  7.089796e+10  4.850156e+10
5    1.186120e+10  1.301973e+10  1.515642e+10  1.540183e+10  1.516273e+10
8    3.692550e+11  3.905170e+11  4.270490e+11  4.179900e+11  3.494730e+11
..            ...           ...           ...           ...           ...
251  1.869510e+13  1.947730e+13  2.053310e+13  2.138100e+13  2.106050e+13
254  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
257  2.570960e+11  2.813540e+11  3.101060e+11  3.343650e+11  3.466160e+11
262  3.131782e+10  2.684223e+10  2.160616e+10  0.000000e+00  0.000000e+00
263  3.235860e+11  3.814490e+11  4.052610e+11  3.893300e+11  3.382910e+11

             2021          2022
0    3.103184e+09  3.544708e+09
2    1.426650e+10  0.000000e+00
4    6.650513e+10  1.067830e+11
5    1.793057e+10  1.891638e+10
8    4.151790e+11  5.070640e+11
..            ...           ...
251  2.331510e+13  2.543970e+13
254  0.000000e+00  0.000000e+00
257  3.661380e+11  4.088020e+11
262  0.000000e+00  0.000000e+00
263  4.201180e+11  4.052710e+11

[101 rows x 67 columns]

In [ ]:

import pandas as pd


columns_to_drop = ['Country Name', 'Indicator Name', 'Indicator Code']
filtered_df7.drop(columns=columns_to_drop, inplace=True)

# Display the modified DataFrame
print(filtered_df7)

    Country Code          1960          1961          1962          1963  \
0            ABW  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
2            AFG  5.377778e+08  5.488889e+08  5.466667e+08  7.511112e+08
4            AGO  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
5            ALB  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
8            ARE  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
..           ...           ...           ...           ...           ...
251          USA  5.433000e+11  5.633000e+11  6.051000e+11  6.386000e+11
254          VEN  7.663938e+09  8.067267e+09  8.814310e+09  9.608717e+09
257          VNM  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
262          YEM  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
263          ZAF  8.748597e+09  9.225996e+09  9.813996e+09  1.085420e+10

             1964          1965          1966          1967          1968  \
0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
2    8.000000e+08  1.006667e+09  1.400000e+09  1.673333e+09  1.373333e+09
4    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
5    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
8    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
..            ...           ...           ...           ...           ...
251  6.858000e+11  7.437000e+11  8.150000e+11  8.617000e+11  9.425000e+11
254  8.192414e+09  8.427778e+09  8.781333e+09  9.250000e+09  1.003444e+10
257  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
262  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
263  1.195600e+10  1.306899e+10  1.421139e+10  1.582139e+10  1.712479e+10

     ...          2013          2014          2015          2016  \
0    ...  2.727850e+09  2.790850e+09  2.962907e+09  2.983635e+09
2    ...  2.014642e+10  2.049713e+10  1.913422e+10  1.811657e+10
4    ...  1.323390e+11  1.359670e+11  9.049642e+10  5.276162e+10
5    ...  1.277622e+10  1.322815e+10  1.138685e+10  1.186120e+10
8    ...  4.002190e+11  4.141050e+11  3.702750e+11  3.692550e+11
..   ...           ...           ...           ...           ...
251  ...  1.684320e+13  1.755070e+13  1.820600e+13  1.869510e+13
254  ...  3.710050e+11  4.823590e+11  0.000000e+00  0.000000e+00
257  ...  2.137090e+11  2.334510e+11  2.392580e+11  2.570960e+11
262  ...  4.041523e+10  4.322859e+10  4.244449e+10  3.131782e+10
263  ...  4.008860e+11  3.811990e+11  3.467100e+11  3.235860e+11

             2017          2018          2019          2020          2021  \
0    3.092429e+09  3.276184e+09  3.395799e+09  2.558906e+09  3.103184e+09
2    1.875346e+10  1.805322e+10  1.879944e+10  1.995593e+10  1.426650e+10
4    7.369016e+10  7.945069e+10  7.089796e+10  4.850156e+10  6.650513e+10
5    1.301973e+10  1.515642e+10  1.540183e+10  1.516273e+10  1.793057e+10
8    3.905170e+11  4.270490e+11  4.179900e+11  3.494730e+11  4.151790e+11
..            ...           ...           ...           ...           ...
251  1.947730e+13  2.053310e+13  2.138100e+13  2.106050e+13  2.331510e+13
254  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
257  2.813540e+11  3.101060e+11  3.343650e+11  3.466160e+11  3.661380e+11
262  2.684223e+10  2.160616e+10  0.000000e+00  0.000000e+00  0.000000e+00
263  3.814490e+11  4.052610e+11  3.893300e+11  3.382910e+11  4.201180e+11

             2022
0    3.544708e+09
2    0.000000e+00
4    1.067830e+11
5    1.891638e+10
8    5.070640e+11
..            ...
251  2.543970e+13
254  0.000000e+00
257  4.088020e+11
262  0.000000e+00
263  4.052710e+11

[101 rows x 64 columns]

<ipython-input-52-e8e0c8ea5f43>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df7.drop(columns=columns_to_drop, inplace=True)

In [ ]:
# Convert numeric columns to numeric type, replacing non-numeric values with NaN
filtered_df7.iloc[:, 1:-1] = filtered_df7.iloc[:, 1:-1].apply(pd.to_numeric, errors='coerce')

# Create a new column 'Combined' with the median of values from '1960' to '1965'
filtered_df7['median_gdp'] = filtered_df7.iloc[:, 1:-1].median(axis=1)


# Display the resulting DataFrame with the new 'Combined' column
print(filtered_df7[['Country Code', 'median_gdp']])

    Country Code    median_gdp
0            ABW  8.184358e+08
2            AFG  1.703333e+09
4            AGO  6.806114e+09
5            ALB  2.039895e+09
8            ARE  5.112680e+10
..           ...           ...
251          USA  6.060635e+12
254          VEN  5.593606e+10
257          VNM  1.519056e+10
262          YEM  0.000000e+00
263          ZAF  1.275680e+11

[101 rows x 2 columns]

<ipython-input-53-87cfe34ce1ce>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df7.iloc[:, 1:-1] = filtered_df7.iloc[:, 1:-1].apply(pd.to_numeric, errors='coerce')
<ipython-input-53-87cfe34ce1ce>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df7['median_gdp'] = filtered_df7.iloc[:, 1:-1].median(axis=1)

In [ ]:
low_threshold = filtered_df7['median_gdp'].quantile(0.33)
high_threshold = filtered_df7['median_gdp'].quantile(0.66)

# Categorize based on thresholds
filtered_df7['Category_median_gdp'] = pd.cut(filtered_df7['median_gdp'], bins=[-float('inf'), low_threshold, high_threshold, float('inf')],
                               labels=['Low', 'Moderate', 'High'])

# Display the result
print(filtered_df7[['Country Code', 'median_gdp', 'Category_median_gdp']])

    Country Code    median_gdp Category_median_gdp
0            ABW  8.184358e+08                 Low
2            AFG  1.703333e+09                 Low
4            AGO  6.806114e+09            Moderate
5            ALB  2.039895e+09                 Low
8            ARE  5.112680e+10            Moderate
..           ...           ...                 ...
251          USA  6.060635e+12                High
254          VEN  5.593606e+10            Moderate
257          VNM  1.519056e+10            Moderate
262          YEM  0.000000e+00                 Low
263          ZAF  1.275680e+11                High

[101 rows x 3 columns]

<ipython-input-54-b4d698365941>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df7['Category_median_gdp'] = pd.cut(filtered_df7['median_gdp'], bins=[-float('inf'), low_threshold, high_threshold, float('inf')],

In [ ]:
filtered_df7.to_csv('filtered_gdp.csv', index = False)

In [ ]:
df6 = pd.read_csv('cropland.csv')

df6.fillna(0, inplace=True)

In [ ]:
filtered_df6 = df6[df1['Country Code'].isin(unique_country_codes)]

# Print the resulting DataFrame
print(filtered_df6)

             Country Name Country Code                       Indicator Name  \
0                   Aruba          ABW  Permanent cropland (% of land area)
2             Afghanistan          AFG  Permanent cropland (% of land area)
4                  Angola          AGO  Permanent cropland (% of land area)
5                 Albania          ALB  Permanent cropland (% of land area)
8    United Arab Emirates          ARE  Permanent cropland (% of land area)
..                    ...          ...                                  ...
251         United States          USA  Permanent cropland (% of land area)
254         Venezuela, RB          VEN  Permanent cropland (% of land area)
257              Viet Nam          VNM  Permanent cropland (% of land area)
262           Yemen, Rep.          YEM  Permanent cropland (% of land area)
263          South Africa          ZAF  Permanent cropland (% of land area)

     Indicator Code  1960      1961      1962      1963      1964      1965  \
0    AG.LND.CROP.ZS   0.0  0.000000  0.000000  0.000000  0.000000  0.000000
2    AG.LND.CROP.ZS   0.0  0.153320  0.153320  0.153320  0.160986  0.168652
4    AG.LND.CROP.ZS   0.0  0.401059  0.401059  0.401059  0.401059  0.401059
5    AG.LND.CROP.ZS   0.0  1.715328  1.861314  2.007299  2.116788  2.262774
8    AG.LND.CROP.ZS   0.0  0.042242  0.042242  0.042242  0.042242  0.056322
..              ...   ...       ...       ...       ...       ...       ...
251  AG.LND.CROP.ZS   0.0  0.205154  0.207010  0.204062  0.204499  0.204499
254  AG.LND.CROP.ZS   0.0  0.659827  0.659827  0.656425  0.654158  0.649623
257  AG.LND.CROP.ZS   0.0  1.443977  1.459338  1.474700  1.490061  1.505423
262  AG.LND.CROP.ZS   0.0  0.142054  0.142054  0.142054  0.142054  0.142054
263  AG.LND.CROP.ZS   0.0  0.152503  0.152503  0.160747  0.164868  0.173112

     ...       2013       2014       2015       2016       2017       2018  \
0    ...   0.000000   0.000000   0.000000   0.000000   0.000000   0.000000
2    ...   0.191650   0.213115   0.222314   0.277509   0.323506   0.331172
4    ...   0.232614   0.240635   0.240635   0.248656   0.252667   0.254271
5    ...   2.890511   2.934307   2.956204   3.036496   3.072993   3.089562
8    ...   0.589975   0.542101   0.544917   0.553365   0.553365   0.554773
..   ...        ...        ...        ...        ...        ...        ...
251  ...   0.295165   0.295165   0.295165   0.295165   0.295165   0.295165
254  ...   0.793606   0.793606   0.793606   0.793606   0.793606   0.793606
257  ...  12.101953  12.197044  14.368999  14.461991  14.481355  14.505358
262  ...   0.564426   0.564426   0.558744   0.549274   0.547380   0.539803
263  ...   0.340453   0.340453   0.340453   0.340453   0.340453   0.340453

          2019       2020       2021  2022
0     0.000000   0.000000   0.000000   0.0
2     0.340371   0.340371   0.340371   0.0
4     0.254271   0.254271   0.254271   0.0
5     3.138686   3.210036   3.198175   0.0
8     0.571670   0.571670   0.580849   0.0
..         ...        ...        ...   ...
251   0.295165   0.295165   0.295165   0.0
254   0.793606   0.793606   0.793606   0.0
257  15.831337  15.732431  15.732431   0.0
262   0.556850   0.556850   0.556850   0.0
263   0.340453   0.340453   0.340453   0.0

[101 rows x 67 columns]

In [ ]:
import pandas as pd


columns_to_drop = ['Country Name', 'Indicator Name', 'Indicator Code']
filtered_df6.drop(columns=columns_to_drop, inplace=True)

# Display the modified DataFrame
print(filtered_df6)

    Country Code  1960      1961      1962      1963      1964      1965  \
0            ABW   0.0  0.000000  0.000000  0.000000  0.000000  0.000000
2            AFG   0.0  0.153320  0.153320  0.153320  0.160986  0.168652
4            AGO   0.0  0.401059  0.401059  0.401059  0.401059  0.401059
5            ALB   0.0  1.715328  1.861314  2.007299  2.116788  2.262774
8            ARE   0.0  0.042242  0.042242  0.042242  0.042242  0.056322
..           ...   ...       ...       ...       ...       ...       ...
251          USA   0.0  0.205154  0.207010  0.204062  0.204499  0.204499
254          VEN   0.0  0.659827  0.659827  0.656425  0.654158  0.649623
257          VNM   0.0  1.443977  1.459338  1.474700  1.490061  1.505423
262          YEM   0.0  0.142054  0.142054  0.142054  0.142054  0.142054
263          ZAF   0.0  0.152503  0.152503  0.160747  0.164868  0.173112

         1966      1967      1968  ...       2013       2014       2015  \
0    0.000000  0.000000  0.000000  ...   0.000000   0.000000   0.000000
2    0.183984  0.206982  0.208515  ...   0.191650   0.213115   0.222314
4    0.401059  0.401059  0.401059  ...   0.232614   0.240635   0.240635
5    2.372263  2.481752  2.554745  ...   2.890511   2.934307   2.956204
8    0.056322  0.056322  0.056322  ...   0.589975   0.542101   0.544917
..        ...       ...       ...  ...        ...        ...        ...
251  0.201442  0.198713  0.195983  ...   0.295165   0.295165   0.295165
254  0.647356  0.650757  0.656425  ...   0.793606   0.793606   0.793606
257  1.520784  1.536146  1.551507  ...  12.101953  12.197044  14.368999
262  0.153418  0.153418  0.153418  ...   0.564426   0.564426   0.558744
263  0.177233  0.189598  0.197842  ...   0.340453   0.340453   0.340453

          2016       2017       2018       2019       2020       2021  2022
0     0.000000   0.000000   0.000000   0.000000   0.000000   0.000000   0.0
2     0.277509   0.323506   0.331172   0.340371   0.340371   0.340371   0.0
4     0.248656   0.252667   0.254271   0.254271   0.254271   0.254271   0.0
5     3.036496   3.072993   3.089562   3.138686   3.210036   3.198175   0.0
8     0.553365   0.553365   0.554773   0.571670   0.571670   0.580849   0.0
..         ...        ...        ...        ...        ...        ...   ...
251   0.295165   0.295165   0.295165   0.295165   0.295165   0.295165   0.0
254   0.793606   0.793606   0.793606   0.793606   0.793606   0.793606   0.0
257  14.461991  14.481355  14.505358  15.831337  15.732431  15.732431   0.0
262   0.549274   0.547380   0.539803   0.556850   0.556850   0.556850   0.0
263   0.340453   0.340453   0.340453   0.340453   0.340453   0.340453   0.0

[101 rows x 64 columns]

<ipython-input-58-18a086266e76>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df6.drop(columns=columns_to_drop, inplace=True)

In [ ]:
# Convert numeric columns to numeric type, replacing non-numeric values with NaN
filtered_df6.iloc[:, 1:-1] = filtered_df6.iloc[:, 1:-1].apply(pd.to_numeric, errors='coerce')

# Create a new column 'Combined' with the median of values from '1960' to '1965'
filtered_df6['median_cropland'] = filtered_df6.iloc[:, 1:-1].median(axis=1)


# Display the resulting DataFrame with the new 'Combined' column
print(filtered_df6[['Country Code', 'median_cropland']])

    Country Code  median_cropland
0            ABW         0.000000
2            AFG         0.199316
4            AGO         0.214566
5            ALB         4.051095
8            ARE         0.316812
..           ...              ...
251          USA         0.229284
254          VEN         0.793606
257          VNM         3.228978
262          YEM         0.195087
263          ZAF         0.249363

[101 rows x 2 columns]

<ipython-input-59-30810ff5a071>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df6.iloc[:, 1:-1] = filtered_df6.iloc[:, 1:-1].apply(pd.to_numeric, errors='coerce')
<ipython-input-59-30810ff5a071>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df6['median_cropland'] = filtered_df6.iloc[:, 1:-1].median(axis=1)

In [ ]:
low_threshold = filtered_df6['median_cropland'].quantile(0.33)
high_threshold = filtered_df6['median_cropland'].quantile(0.66)

# Categorize based on thresholds
filtered_df6['Category_median_cropland'] = pd.cut(filtered_df6['median_cropland'], bins=[-float('inf'), low_threshold, high_threshold, float('inf')],
                               labels=['Low', 'Moderate', 'High'])

# Display the result
print(filtered_df6[['Country Code', 'median_cropland', 'Category_median_cropland']])

    Country Code  median_cropland Category_median_cropland
0            ABW         0.000000                      Low
2            AFG         0.199316                      Low
4            AGO         0.214566                      Low
5            ALB         4.051095                     High
8            ARE         0.316812                 Moderate
..           ...              ...                      ...
251          USA         0.229284                      Low
254          VEN         0.793606                 Moderate
257          VNM         3.228978                     High
262          YEM         0.195087                      Low
263          ZAF         0.249363                      Low

[101 rows x 3 columns]

<ipython-input-60-4498e755b6e6>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df6['Category_median_cropland'] = pd.cut(filtered_df6['median_cropland'], bins=[-float('inf'), low_threshold, high_threshold, float('inf')],

In [ ]:
filtered_df6.to_csv('filtered_cropland.csv', index = False)

In [ ]:
cmaff = filtered_df4[['Country Code','Category_median_aff']]
cmf = filtered_df5['Category_median_fertilizer']
cmc = filtered_df6['Category_median_cropland']
cmgdp = filtered_df7['Category_median_gdp']

In [ ]:
result = pd.concat([cmaff,cmf,cmc,cmgdp], axis=1)
result.head()

,Country Code,Category_median_aff,Category_median_fertilizer,Category_median_cropland,Category_median_gdp
0,ABW,Low,Low,Low,Low
2,AFG,Low,Moderate,Low,Low
4,AGO,Low,Low,Low,Moderate
5,ALB,Low,Moderate,High,Low
8,ARE,Moderate,Moderate,Moderate,Moderate

In [ ]:
result.to_csv('result.csv', index=False)

In [ ]:
import pandas as pd

# Assuming 'result' is your DataFrame and you want to get value counts for columns 'cmaff', 'cmf', 'cmc', and 'cmgd'
columns_of_interest = ['Category_median_aff','Category_median_fertilizer',	'Category_median_cropland',	'Category_median_gdp']
combined_series = result[columns_of_interest].apply(tuple, axis=1)
value_counts = combined_series.value_counts()

print(value_counts)

(Low, Low, Low, Low)                        8
(High, Low, Moderate, Low)                  6
(Moderate, High, Low, High)                 5
(High, High, High, Moderate)                5
(High, Low, High, Moderate)                 4
(Low, Low, High, Low)                       4
(High, High, High, High)                    4
(Moderate, Moderate, Moderate, Moderate)    4
(Moderate, Moderate, Moderate, High)        3
(Low, Moderate, Low, High)                  3
(Moderate, High, Moderate, High)            3
(Low, Moderate, Low, Moderate)              3
(High, Low, Low, Low)                       3
(High, High, Moderate, High)                3
(Moderate, Moderate, Low, High)             3
(Low, High, Low, Moderate)                  2
(High, Low, High, Low)                      2
(Moderate, High, High, High)                2
(Moderate, High, Low, Moderate)             2
(Low, Moderate, High, High)                 2
(High, Moderate, Moderate, Moderate)        2
(Low, Moderate, High, Low)                  2
(High, High, Moderate, Moderate)            2
(Moderate, Low, Moderate, Low)              2
(Moderate, Moderate, High, Moderate)        2
(Low, Low, Low, Moderate)                   2
(Moderate, High, High, Moderate)            1
(Moderate, Moderate, High, Low)             1
(Moderate, Low, Moderate, Moderate)         1
(High, Moderate, Low, Low)                  1
(Moderate, Low, Low, High)                  1
(Low, Moderate, Moderate, High)             1
(Moderate, High, Moderate, Moderate)        1
(Low, High, Moderate, Low)                  1
(Moderate, Moderate, Moderate, Low)         1
(Low, High, Moderate, High)                 1
(Low, Moderate, Low, Low)                   1
(High, Moderate, High, High)                1
(Low, High, High, Moderate)                 1
(Low, Low, Moderate, High)                  1
(Low, High, High, High)                     1
(Moderate, Low, High, Low)                  1
(Low, Low, Moderate, Low)                   1
(High, Moderate, High, Moderate)            1
dtype: int64

In [ ]:
import pandas as pd

# Assuming 'result' is your DataFrame
columns_of_interest = ['Category_median_aff','Category_median_fertilizer','Category_median_cropland','Category_median_gdp']

# Loop through each column of interest and count occurrences of 'Low', 'Moderate', 'High'
for column in columns_of_interest:
    column_counts = result[column].value_counts()
    print(f"Counts for '{column}':")
    print(column_counts)

Counts for 'Category_median_aff':
Low         34
High        34
Moderate    33
Name: Category_median_aff, dtype: int64
Counts for 'Category_median_fertilizer':
Low         36
High        34
Moderate    31
Name: Category_median_fertilizer, dtype: int64
Counts for 'Category_median_cropland':
Low         34
High        34
Moderate    33
Name: Category_median_cropland, dtype: int64
Counts for 'Category_median_gdp':
Low         34
High        34
Moderate    33
Name: Category_median_gdp, dtype: int64

In [ ]:
# Assuming 'result' is your DataFrame
columns_of_interest = ['Category_median_aff', 'Category_median_fertilizer', 'Category_median_cropland', 'Category_median_gdp']

# Create a boolean mask to filter rows where all specified columns have the value 'Low'
mask = (result[columns_of_interest] == 'Low').all(axis=1)

# Use the mask to filter the DataFrame and retrieve rows where all specified columns have 'Low'
rows_with_all_low = result[mask]
print(rows_with_all_low)

    Country Code Category_median_aff Category_median_fertilizer  \
0            ABW                 Low                        Low
27           BMU                 Low                        Low
78           FRO                 Low                        Low
84           GIB                 Low                        Low
91           GRL                 Low                        Low
146          MAC                 Low                        Low
172          NCL                 Low                        Low
262          YEM                 Low                        Low

    Category_median_cropland Category_median_gdp
0                        Low                 Low
27                       Low                 Low
78                       Low                 Low
84                       Low                 Low
91                       Low                 Low
146                      Low                 Low
172                      Low                 Low
262                      Low                 Low

In [ ]:
maff = filtered_df4[['Country Code','median_aff']]
mf = filtered_df5['median_fertilizer']
mc = filtered_df6['median_cropland']
mgdp = filtered_df7['median_gdp']

In [ ]:
result2 = pd.concat([maff,mf,mc,mgdp], axis=1)
result2.head()

  Country Code  median_aff  median_fertilizer  median_cropland    median_gdp
0          ABW    0.000000           0.000000         0.000000  8.184358e+08
2          AFG    0.000000         104.651853         0.199316  1.703333e+09
4          AGO    0.000000           0.000000         0.214566  6.806114e+09
5          ALB    0.000000         101.111029         4.051095  2.039895e+09
8          ARE    0.740869           3.378659         0.316812  5.112680e+10

In [ ]:
result2.to_csv('result2.csv', index=False)

In [ ]:
country_codes = ['ABW', 'BMU', 'FRO', 'GIB', 'GRL', 'MAC', 'NCL', 'YEM']

# Filtering and printing rows with the specified 'Country Code'
filtered_countries = result[result['Country Code'].isin(country_codes)]
print(filtered_countries)

    Country Code Category_median_aff Category_median_fertilizer  \
0            ABW                 Low                        Low
27           BMU                 Low                        Low
78           FRO                 Low                        Low
84           GIB                 Low                        Low
91           GRL                 Low                        Low
146          MAC                 Low                        Low
172          NCL                 Low                        Low
262          YEM                 Low                        Low

    Category_median_cropland Category_median_gdp
0                        Low                 Low
27                       Low                 Low
78                       Low                 Low
84                       Low                 Low
91                       Low                 Low
146                      Low                 Low
172                      Low                 Low
262                      Low                 Low

In [ ]:
df_final = pd.read_csv('result.csv')

In [ ]:
df_final = df_final.drop('Category_median_gdp', axis=1)

In [ ]:
df_final

,Country Code,Category_median_aff,Category_median_fertilizer,Category_median_cropland
0,ABW,Low,Low,Low
1,AFG,Low,Moderate,Low
2,AGO,Low,Low,Low
3,ALB,Low,Moderate,High
4,ARE,Moderate,Moderate,Moderate
...,...,...,...,...
96,USA,Low,Moderate,Low
97,VEN,Moderate,Moderate,Moderate
98,VNM,High,High,High
99,YEM,Low,Low,Low
100,ZAF,Moderate,High,Low

In [ ]:
conditions = [
    (df_final['Category_median_aff'] == 'Low') & (df_final['Category_median_fertilizer'] == 'Low') &
    (df_final['Category_median_cropland'] == 'Low'),
    (df_final['Category_median_aff'] == 'Low') & (df_final['Category_median_fertilizer'] == 'Low') &
    (df_final['Category_median_cropland'] == 'Moderate'),
    # Add more initial conditions as needed
]

categories = ['Poor', 'AnotherCategory']
# Add more initial categories as needed

In [ ]:
conditions += [
    (df_final['Category_median_aff'] == 'Moderate') & (df_final['Category_median_fertilizer'] == 'Low') &
    (df_final['Category_median_cropland'] == 'Low'),
    (df_final['Category_median_aff'] == 'High') & (df_final['Category_median_fertilizer'] == 'Moderate') &
    (df_final['Category_median_cropland'] == 'Moderate')
    # Add more conditions as needed
]

categories += ['AnotherCategory', 'YetAnotherCategory']
# Add more categories as needed

In [ ]:
import numpy as np

In [ ]:
# Assuming df_final is your original DataFrame

# Define your conditions and categories
conditions = [
    (df_final['Category_median_aff'] == 'Low') & (df_final['Category_median_fertilizer'] == 'Low') &
    (df_final['Category_median_cropland'] == 'Low'),
    (df_final['Category_median_aff'] == 'Low') & (df_final['Category_median_fertilizer'] == 'Low') &
    (df_final['Category_median_cropland'] == 'Moderate'),
    # Add more conditions as needed
]

categories = ['Low', 'Moderate']
# Add more categories as needed

# Additional conditions and categories
conditions += [
    (df_final['Category_median_aff'] == 'Moderate') & (df_final['Category_median_fertilizer'] == 'Low') &
    (df_final['Category_median_cropland'] == 'Low'),
    (df_final['Category_median_aff'] == 'High') & (df_final['Category_median_fertilizer'] == 'Moderate') &
    (df_final['Category_median_cropland'] == 'Moderate'),
    # Add more conditions as needed
]

categories += ['Moderate', 'High']
# Add more categories as needed

# Create a new column 'NewCategory' based on conditions and categories
df_final['NewCategory'] = np.select(conditions, categories, default='Uncategorized')

# Save the updated DataFrame to a new CSV file
df_final.to_csv('updated_categories.csv', index=False)

In [ ]:
import pandas as pd

# Assuming 'result' is your DataFrame and you want to get value counts for columns 'cmaff', 'cmf', 'cmc', and 'cmgd'
columns_of_interest = ['Category_median_aff','Category_median_fertilizer',	'Category_median_cropland']
combined_series = df_final[columns_of_interest].apply(tuple, axis=1)
value_counts = combined_series.value_counts()

print(value_counts)

(Low, Low, Low)                   10
(High, High, High)                 9
(Moderate, Moderate, Moderate)     8
(Low, Moderate, Low)               7
(Moderate, High, Low)              7
(High, Low, Moderate)              6
(High, Low, High)                  6
(High, High, Moderate)             5
(Low, Moderate, High)              4
(Moderate, High, Moderate)         4
(Low, Low, High)                   4
(Moderate, Moderate, Low)          3
(Moderate, High, High)             3
(Moderate, Low, Moderate)          3
(High, Low, Low)                   3
(Moderate, Moderate, High)         3
(Low, Low, Moderate)               2
(Low, High, Low)                   2
(High, Moderate, Moderate)         2
(Low, High, High)                  2
(High, Moderate, High)             2
(Low, High, Moderate)              2
(Moderate, Low, High)              1
(Low, Moderate, Moderate)          1
(Moderate, Low, Low)               1
(High, Moderate, Low)              1
dtype: int64

In [ ]:
df_final

,Country Code,Category_median_aff,Category_median_fertilizer,Category_median_cropland,NewCategory
0,ABW,Low,Low,Low,Low
1,AFG,Low,Moderate,Low,Uncategorized
2,AGO,Low,Low,Low,Low
3,ALB,Low,Moderate,High,Uncategorized
4,ARE,Moderate,Moderate,Moderate,Uncategorized
...,...,...,...,...,...
96,USA,Low,Moderate,Low,Uncategorized
97,VEN,Moderate,Moderate,Moderate,Uncategorized
98,VNM,High,High,High,Uncategorized
99,YEM,Low,Low,Low,Low
100,ZAF,Moderate,High,Low,Uncategorized

In [ ]:
import pandas as pd
import numpy as np

# Assuming df_final is your DataFrame

# Define your conditions and corresponding labels
conditions = [
    (df_final['Category_median_aff'] == 'Low') & (df_final['Category_median_fertilizer'] == 'Low') & (df_final['Category_median_cropland'] == 'Low'),
    (df_final['Category_median_aff'] == 'High') & (df_final['Category_median_fertilizer'] == 'High') & (df_final['Category_median_cropland'] == 'High'),
    (df_final['Category_median_aff'] == 'Moderate') & (df_final['Category_median_fertilizer'] == 'Moderate') & (df_final['Category_median_cropland'] == 'Moderate'),

    (df_final['Category_median_aff'] == 'Low') & (df_final['Category_median_fertilizer'] == 'Moderate') & (df_final['Category_median_cropland'] == 'Low'),
    (df_final['Category_median_aff'] == 'Moderate') & (df_final['Category_median_fertilizer'] == 'High') & (df_final['Category_median_cropland'] == 'Low'),
    (df_final['Category_median_aff'] == 'High') & (df_final['Category_median_fertilizer'] == 'Low') & (df_final['Category_median_cropland'] == 'Moderate'),
    (df_final['Category_median_aff'] == 'High') & (df_final['Category_median_fertilizer'] == 'Low') & (df_final['Category_median_cropland'] == 'High'),

    # Additional conditions
    (df_final['Category_median_aff'] == 'Low') & (df_final['Category_median_fertilizer'] == 'Low') & (df_final['Category_median_cropland'] == 'Moderate'),
    (df_final['Category_median_aff'] == 'Moderate') & (df_final['Category_median_fertilizer'] == 'Moderate') & (df_final['Category_median_cropland'] == 'Low'),
    (df_final['Category_median_aff'] == 'Low') & (df_final['Category_median_fertilizer'] == 'High') & (df_final['Category_median_cropland'] == 'High'),



]

categories = ['Low', 'High', 'Moderate', 'Low-Moderate', 'Moderate-High', 'High-Low', 'High-High', 'Low-Moderate2', 'Moderate-Low', 'High-High2']

conditions += [
    (df_final['Category_median_aff'] == 'Moderate') & (df_final['Category_median_fertilizer'] == 'Low') & (df_final['Category_median_cropland'] == 'Moderate'),
    (df_final['Category_median_aff'] == 'Low') & (df_final['Category_median_fertilizer'] == 'Moderate') & (df_final['Category_median_cropland'] == 'High'),
    (df_final['Category_median_aff'] == 'High') & (df_final['Category_median_fertilizer'] == 'Moderate') & (df_final['Category_median_cropland'] == 'High'),
    (df_final['Category_median_aff'] == 'Moderate') & (df_final['Category_median_fertilizer'] == 'High') & (df_final['Category_median_cropland'] == 'Moderate'),
    (df_final['Category_median_aff'] == 'High') & (df_final['Category_median_fertilizer'] == 'Moderate') & (df_final['Category_median_cropland'] == 'Low'),
    (df_final['Category_median_aff'] == 'Low') & (df_final['Category_median_fertilizer'] == 'High') & (df_final['Category_median_cropland'] == 'Moderate'),
    (df_final['Category_median_aff'] == 'Moderate') & (df_final['Category_median_fertilizer'] == 'Low') & (df_final['Category_median_cropland'] == 'High'),
    (df_final['Category_median_aff'] == 'High') & (df_final['Category_median_fertilizer'] == 'High') & (df_final['Category_median_cropland'] == 'Moderate'),
    (df_final['Category_median_aff'] == 'High') & (df_final['Category_median_fertilizer'] == 'Moderate') & (df_final['Category_median_cropland'] == 'Low'),
    (df_final['Category_median_aff'] == 'Low') & (df_final['Category_median_fertilizer'] == 'High') & (df_final['Category_median_cropland'] == 'High'),
    # Add more conditions as needed
]

# Additional categories
categories += ['Moderate', 'Moderate', 'High', 'Moderate', 'Low', 'Moderate', 'High', 'High', 'Moderate', 'High']
# Add more categories as needed

# Create a new column 'OverallCategory' based on conditions and categories
df_final['OverallCategory'] = np.select(conditions, categories, default='Uncategorized')

# Save the updated DataFrame to a new CSV file
df_final.to_csv('final_categories.csv', index=False)

In [ ]:
df_final.drop('NewCategory', axis=1, inplace=True)

# Save the updated DataFrame to a new CSV file without 'NewCategory' column
df_final.to_csv('updated_categories_without_NewCategory.csv', index=False)

In [ ]:
overall_categories = df_final['OverallCategory'].value_counts()

# Print overall categories and the number of countries in each category
print("Overall Categories and Number of Countries:")
print(overall_categories)

Overall Categories and Number of Countries:
Moderate         21
Uncategorized    19
High             17
Low              11
Low-Moderate      7
Moderate-High     7
High-Low          6
High-High         6
Moderate-Low      3
Low-Moderate2     2
High-High2        2
Name: OverallCategory, dtype: int64

In [ ]:
# Assuming df_final is your DataFrame
overall_categories = df_final['OverallCategory'].value_counts()

# Print overall categories and the number of countries in each category
print("Overall Categories and Number of Countries:")
print(overall_categories)

# Print countries where overall category is 'Uncategorized'
uncategorized_countries = df_final[df_final['OverallCategory'] == 'Uncategorized']['Country Code'].tolist()
print("\nCountries where Overall Category is 'Uncategorized':")
print(uncategorized_countries)

Overall Categories and Number of Countries:
Moderate         21
Uncategorized    19
High             17
Low              11
Low-Moderate      7
Moderate-High     7
High-Low          6
High-High         6
Moderate-Low      3
Low-Moderate2     2
High-High2        2
Name: OverallCategory, dtype: int64

Countries where Overall Category is 'Uncategorized':
['BGR', 'BHR', 'BOL', 'COG', 'CUB', 'CYM', 'DZA', 'EGY', 'FRA', 'GNQ', 'IRL', 'ITA', 'MAR', 'POL', 'PYF', 'ROU', 'RUS', 'SUR', 'TTO']

In [ ]:
# Assuming df_final is your DataFrame

# Create a dictionary to store countries for each category
countries_by_category = {}

# List of categories and corresponding counts
categories_counts = {
    'Moderate': 21,
    'Uncategorized': 19,
    'High': 17,
    'Low': 11,
    'Low-Moderate': 7,
    'Moderate-High': 7,
    'High-Low': 6,
    'High-High': 6,
    'Moderate-Low': 3,
    'Low-Moderate2': 2,
    'High-High2': 2
}

# Iterate over each category and extract corresponding countries
for category, count in categories_counts.items():
    # Filter rows where 'OverallCategory' is equal to the current category
    category_countries = df_final[df_final['OverallCategory'] == category]['Country Code'].tolist()[:count]

    # Add the list of countries to the dictionary
    countries_by_category[category] = category_countries

# Print the result
for category, countries in countries_by_category.items():
    print(f"{category} Countries ({len(countries)}): {countries}")

Moderate Countries (21): ['ALB', 'ARE', 'ARG', 'AUT', 'BRN', 'CHE', 'CHL', 'ESP', 'GAB', 'IRQ', 'ISR', 'JOR', 'JPN', 'KOR', 'MEX', 'MMR', 'NLD', 'PER', 'PRT', 'SGP', 'VEN']
Uncategorized Countries (19): ['BGR', 'BHR', 'BOL', 'COG', 'CUB', 'CYM', 'DZA', 'EGY', 'FRA', 'GNQ', 'IRL', 'ITA', 'MAR', 'POL', 'PYF', 'ROU', 'RUS', 'SUR', 'TTO']
High Countries (17): ['BGD', 'BRA', 'BRB', 'CHN', 'COL', 'IDN', 'IND', 'IRN', 'MYS', 'NGA', 'PAK', 'PHL', 'SYR', 'THA', 'TUN', 'TUR', 'VNM']
Low Countries (11): ['ABW', 'AGO', 'BMU', 'FRO', 'GIB', 'GRL', 'LUX', 'MAC', 'NCL', 'SEN', 'YEM']
Low-Moderate Countries (7): ['AFG', 'BEL', 'CAN', 'KWT', 'LBY', 'QAT', 'USA']
Moderate-High Countries (7): ['AUS', 'DNK', 'GBR', 'NZL', 'SWE', 'URY', 'ZAF']
High-Low Countries (6): ['BLZ', 'GMB', 'MOZ', 'PNG', 'TGO', 'TZA']
High-High Countries (6): ['CIV', 'CMR', 'DOM', 'ECU', 'GHA', 'RWA']
Moderate-Low Countries (3): ['FIN', 'NOR', 'SAU']
Low-Moderate2 Countries (2): ['COD', 'HKG']
High-High2 Countries (2): ['GRC', 'HUN']

In [ ]:
import pandas as pd
df = pd.read_csv('2ndnew_table_filled.csv')

In [ ]:
zero_rows = df[(df.loc[:, '1960':'2022'] == 0).all(axis=1)]

zero_rows.to_csv('zero_rows.csv', index=False)